baseURL = 'https://b.rohman.dev/'
title = 'rhxxx'
languageCode = 'id-ID'

theme = 'hugo-theme-console'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn slow" 

  [[params.navlinks]]
  name = "about/"
  url = "about/"
